[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle uploads directory
[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Ensure uploads directories exist and are writable
[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "netlify-plugin-mkdir"
  [plugins.inputs]
    dirs = [
      "public/uploads/accounts",
      "public/uploads/receipts"
    ]

